# `cmake --build <preset> --target appimage` -> build/<preset>/Mira-x86_64.AppImage
#
# Bundles mirad + mira + mira-gui into a single self-contained AppImage,
# the non-Arch install path the AUR PKGBUILD doesn't cover. Only defined
# when mira-gui itself was built (see the guard at the include site in the
# root CMakeLists.txt): an AppImage with nothing to launch isn't useful.
#
# The packaging tools (linuxdeploy, linuxdeploy-plugin-qt) are fetched via
# curl into build/<preset>/appimage-tools/ on first use and cached there,
# the same shell-out-to-curl-rather-than-link pattern already used for
# Proton-GE/Wine-GE downloads (see src/runner/Downloader.cpp), applied here
# to a build-time tool instead of a runtime one. Nothing is installed
# system-wide and nothing is required beyond curl, which the backend already
# depends on at runtime.

set(MIRA_APPIMAGE_TOOLS_DIR "${CMAKE_BINARY_DIR}/appimage-tools")
set(MIRA_APPDIR "${CMAKE_BINARY_DIR}/AppDir")

set(MIRA_LINUXDEPLOY_URL
    "https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage")
set(MIRA_LINUXDEPLOY_QT_URL
    "https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage")
set(MIRA_LINUXDEPLOY "${MIRA_APPIMAGE_TOOLS_DIR}/linuxdeploy-x86_64.AppImage")
set(MIRA_LINUXDEPLOY_QT "${MIRA_APPIMAGE_TOOLS_DIR}/linuxdeploy-plugin-qt-x86_64.AppImage")

add_custom_command(
  OUTPUT "${MIRA_LINUXDEPLOY}"
  COMMAND "${CMAKE_COMMAND}" -E make_directory "${MIRA_APPIMAGE_TOOLS_DIR}"
  COMMAND curl -sSL -o "${MIRA_LINUXDEPLOY}" "${MIRA_LINUXDEPLOY_URL}"
  COMMAND chmod +x "${MIRA_LINUXDEPLOY}"
  COMMENT "Downloading linuxdeploy"
  VERBATIM)

add_custom_command(
  OUTPUT "${MIRA_LINUXDEPLOY_QT}"
  COMMAND "${CMAKE_COMMAND}" -E make_directory "${MIRA_APPIMAGE_TOOLS_DIR}"
  COMMAND curl -sSL -o "${MIRA_LINUXDEPLOY_QT}" "${MIRA_LINUXDEPLOY_QT_URL}"
  COMMAND chmod +x "${MIRA_LINUXDEPLOY_QT}"
  COMMENT "Downloading linuxdeploy-plugin-qt"
  VERBATIM)

# linuxdeploy-plugin-qt needs QMAKE pointed at this Qt's own qmake to bundle
# the right Qt libs/plugins version. Qt6's CMake package doesn't reliably
# expose an importable qmake target across Qt versions, so this is resolved
# the same way a shell script would: search next to where Qt6Config.cmake
# itself was found, then fall back to PATH.
find_program(MIRA_QMAKE_EXECUTABLE
  NAMES qmake6 qmake
  HINTS "${Qt6_DIR}/../../../bin" "${Qt6_DIR}/../../../../bin")
if(NOT MIRA_QMAKE_EXECUTABLE)
  message(WARNING "qmake6 not found near Qt6_DIR (${Qt6_DIR}) or on PATH, "
                  "skipping the 'appimage' target; install qmake6 or set "
                  "MIRA_QMAKE_EXECUTABLE manually and reconfigure.")
else()
  # linuxdeploy-plugin-qt deploys every plugin it finds under
  # `qmake -query QT_INSTALL_PLUGINS`, including third-party ones from the
  # system's kimageformats package (HEIF/EXR/AVIF/... support Mira's blank
  # window has no use for), and on at least one real machine, kimg_heif.so
  # depends on a libheif.so.1 linuxdeploy can't resolve, which fails the
  # whole deploy. There's no include/exclude flag for this, so the fix is a
  # filtered copy of the real plugins tree (missing only the offending
  # kimg_*.so files) plus a qmake wrapper that answers
  # `-query QT_INSTALL_PLUGINS` with that copy and delegates every other
  # query to the real qmake6, redirecting linuxdeploy-plugin-qt's own
  # discovery without touching the system's actual Qt install.
  execute_process(
    COMMAND "${MIRA_QMAKE_EXECUTABLE}" -query QT_INSTALL_PLUGINS
    OUTPUT_VARIABLE MIRA_QT_REAL_PLUGINS_DIR
    OUTPUT_STRIP_TRAILING_WHITESPACE)

  set(MIRA_QT_FILTERED_PLUGINS_DIR "${MIRA_APPIMAGE_TOOLS_DIR}/qt-plugins-filtered")
  set(MIRA_QMAKE_WRAPPER "${MIRA_APPIMAGE_TOOLS_DIR}/qmake-wrapper.sh")
  # linuxdeploy-plugin-qt's actual query (confirmed by reading its
  # src/util.cpp queryQmake()) is a *bare* `qmake -query` with no key
  # argument -- it parses every "KEY:value" line out of the full dump
  # itself. A wrapper that only special-cased the two-argument
  # `-query QT_INSTALL_PLUGINS` form (the more "obvious" guess) never
  # matches and silently falls through to the real qmake every time, which
  # is exactly why an earlier version of this file didn't work: the log
  # kept showing the real /usr/lib/qt6/plugins path. The two-argument form
  # is still handled too, in case some other caller uses it.
  file(WRITE "${MIRA_QMAKE_WRAPPER}" "\
#!/bin/sh
# Generated by cmake/AppImage.cmake -- redirects QT_INSTALL_PLUGINS to a
# filtered copy of the real Qt plugins dir; every other query goes to the
# real qmake unmodified.
REAL_QMAKE=\"${MIRA_QMAKE_EXECUTABLE}\"
FILTERED=\"${MIRA_QT_FILTERED_PLUGINS_DIR}\"
if [ \"$1\" = \"-query\" ] && [ \"$2\" = \"QT_INSTALL_PLUGINS\" ]; then
  echo \"\$FILTERED\"
elif [ \"$1\" = \"-query\" ] && [ -z \"$2\" ]; then
  \"\$REAL_QMAKE\" -query | sed \"s|^QT_INSTALL_PLUGINS:.*|QT_INSTALL_PLUGINS:\$FILTERED|\"
else
  exec \"\$REAL_QMAKE\" \"$@\"
fi
")
  file(CHMOD "${MIRA_QMAKE_WRAPPER}" PERMISSIONS
       OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)

  # linuxdeploy-plugin-qt only ever bundles the xcb platform plugin, not
  # wayland (confirmed by reading its deploy log; no patchelf here to fix
  # up a manually-added Wayland plugin's rpath either). mira-gui runs fine
  # through XWayland, so this makes that the deliberate, quiet default
  # instead of a logged "Could not find the Qt platform plugin wayland".
  # Overridable by anyone who sets QT_QPA_PLATFORM themselves.
  #
  # Written before linuxdeploy runs: it only generates its own AppRun when
  # none exists yet.
  # The compiler's own C++ runtime, bundled so the GUI runs where the system's libstdc++ is older
  # than the one the compiler built it against (GCC 13 on Ubuntu 22.04). Only worth it when that
  # runtime was itself built against an old glibc, as in the container build, so it is opt-in.
  option(MIRA_BUNDLE_CXX_RUNTIME "Bundle libstdc++ and libgcc_s into the AppImage" OFF)
  set(MIRA_BUNDLED_RUNTIME_ARGS "")
  if(MIRA_BUNDLE_CXX_RUNTIME)
    foreach(runtime_lib libstdc++.so.6 libgcc_s.so.1)
      execute_process(COMMAND "${CMAKE_CXX_COMPILER}" -print-file-name=${runtime_lib}
                      OUTPUT_VARIABLE runtime_path OUTPUT_STRIP_TRAILING_WHITESPACE)
      if(IS_ABSOLUTE "${runtime_path}" AND EXISTS "${runtime_path}")
        get_filename_component(runtime_path "${runtime_path}" REALPATH)
        list(APPEND MIRA_BUNDLED_RUNTIME_ARGS --library "${runtime_path}")
      endif()
    endforeach()
  endif()

  set(MIRA_APPRUN "${MIRA_APPIMAGE_TOOLS_DIR}/AppRun")
  file(WRITE "${MIRA_APPRUN}" "\
#!/bin/sh
HERE=\"$(dirname \"$(readlink -f \"$0\")\")\"
export QT_QPA_PLATFORM=\"\${QT_QPA_PLATFORM:-xcb}\"
if [ \"\$1\" = setup ]; then exec \"\$HERE/usr/bin/mira\" \"$@\"; fi
exec \"\$HERE/usr/bin/mira-gui\" \"$@\"
")
  file(CHMOD "${MIRA_APPRUN}" PERMISSIONS
       OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)

  # Guarded by the same `if(MIRA_QMAKE_EXECUTABLE)` as the wrapper script
  # above: without qmake, MIRA_QT_FILTERED_PLUGINS_DIR/MIRA_QMAKE_WRAPPER
  # are unset, and defining this target anyway would substitute empty
  # strings into the commands below, which is a confusing failure deep inside the
  # build instead of the clear one-line warning above. No target beats a
  # broken one.
  add_custom_target(appimage
    COMMAND "${CMAKE_COMMAND}" -E rm -rf "${MIRA_APPDIR}"
    COMMAND "${CMAKE_COMMAND}" -E make_directory "${MIRA_APPDIR}/usr/bin"
    COMMAND "${CMAKE_COMMAND}" -E make_directory "${MIRA_APPDIR}/usr/share/applications"
    COMMAND "${CMAKE_COMMAND}" -E make_directory "${MIRA_APPDIR}/usr/share/icons/hicolor/256x256/apps"
    COMMAND "${CMAKE_COMMAND}" -E copy "$<TARGET_FILE:mirad>" "${MIRA_APPDIR}/usr/bin/mirad"
    COMMAND "${CMAKE_COMMAND}" -E copy "$<TARGET_FILE:mira>" "${MIRA_APPDIR}/usr/bin/mira"
    COMMAND "${CMAKE_COMMAND}" -E copy "$<TARGET_FILE:mira-run>" "${MIRA_APPDIR}/usr/bin/mira-run"
    COMMAND "${CMAKE_COMMAND}" -E copy "$<TARGET_FILE:mira-gui>" "${MIRA_APPDIR}/usr/bin/mira-gui"
    COMMAND "${CMAKE_COMMAND}" -E copy
            "${CMAKE_SOURCE_DIR}/packaging/mira.desktop"
            "${MIRA_APPDIR}/usr/share/applications/mira.desktop"
    COMMAND "${CMAKE_COMMAND}" -E copy
            "${CMAKE_SOURCE_DIR}/packaging/icons/hicolor/256x256/apps/mira.png"
            "${MIRA_APPDIR}/usr/share/icons/hicolor/256x256/apps/mira.png"
    # Rebuilt every time rather than cached: cheap (a few MB of plugin .so
    # files, a local copy), and guarantees it always matches whatever's
    # currently installed rather than a stale snapshot from first configure.
    COMMAND "${CMAKE_COMMAND}" -E rm -rf "${MIRA_QT_FILTERED_PLUGINS_DIR}"
    COMMAND "${CMAKE_COMMAND}" -E copy_directory "${MIRA_QT_REAL_PLUGINS_DIR}" "${MIRA_QT_FILTERED_PLUGINS_DIR}"
    COMMAND sh -c "rm -f '${MIRA_QT_FILTERED_PLUGINS_DIR}'/imageformats/kimg_*.so"
    COMMAND "${CMAKE_COMMAND}" -E make_directory "${MIRA_APPDIR}"
    COMMAND "${CMAKE_COMMAND}" -E copy "${MIRA_APPRUN}" "${MIRA_APPDIR}/AppRun"
    COMMAND chmod 755 "${MIRA_APPDIR}/AppRun"
    # NO_STRIP: linuxdeploy bundles its own `strip`, which on at least one
    # real machine (very new binutils/ld defaults, e.g. RELR relative
    # relocations) can't parse some system libraries it's asked to strip
    # ("unknown type [0x13] section .relr.dyn") and aborts the whole deploy
    # over what's purely a size optimization. Confirmed via the linuxdeploy
    # binary's own embedded strings (not in --help) that this env var exists
    # and skips stripping entirely.
    COMMAND "${CMAKE_COMMAND}" -E env
            "QMAKE=${MIRA_QMAKE_WRAPPER}"
            "LINUXDEPLOY_PLUGIN_QT=${MIRA_LINUXDEPLOY_QT}"
            "NO_STRIP=1"
            "${MIRA_LINUXDEPLOY}"
              --appdir "${MIRA_APPDIR}"
              --executable "${MIRA_APPDIR}/usr/bin/mirad"
              --executable "${MIRA_APPDIR}/usr/bin/mira"
              --executable "${MIRA_APPDIR}/usr/bin/mira-run"
              --executable "${MIRA_APPDIR}/usr/bin/mira-gui"
              --desktop-file "${MIRA_APPDIR}/usr/share/applications/mira.desktop"
              --icon-file "${MIRA_APPDIR}/usr/share/icons/hicolor/256x256/apps/mira.png"
              ${MIRA_BUNDLED_RUNTIME_ARGS}
              --plugin qt
              --output appimage
    WORKING_DIRECTORY "${CMAKE_BINARY_DIR}"
    DEPENDS mirad mira mira-run mira-gui "${MIRA_LINUXDEPLOY}" "${MIRA_LINUXDEPLOY_QT}"
    COMMENT "Building Mira AppImage"
    VERBATIM)
endif()
